### ISSUE TITLE
Funny little search symbol

### ISSUE THREAD

**Issue by morgantaschuk** [pughlab/tracker#10]
Running on Ubuntu 14.04, I see a funny little character next to the search box instead of (I assume) a search button. 

![search-symbol](https://cloud.githubusercontent.com/assets/1746206/8383785/6a5f3724-1c0a-11e5-9cec-307242c60847.png)

**Comment by morungos** [comment]
Yes, I've seen that too. I'm fairly sure it's some weirdness in the URL for the glyphicons webfont, probably due to less configuration muckup.
