### ISSUE TITLE
Add a query language

### ISSUE THREAD

**Issue by morungos** [pughlab/tracker#16]
We need a query language of some kind. Several users have approached us about this, so it is about time that we look into providing it. Note that the current filtering is more search-based, and we probably need both.

**Comment by morgantaschuk** [comment]
+1. Having some kind of advanced search/filtering mechanism would be highly desireable.

**Comment by morungos** [comment]
Basic (well semi-advanced) filtering is now present in 2.1.0-RC2. This is "Excel-like-plus" with a row of filters you can use. These also allow filtering like N/A, and explicitly blank, as well as wildcards (which is a step ahead of Excel). There's a mini query language in this, which allows boolean AND/OR as well, so values like "*FGR* OR ERBB*" should work. I'm closing for now, and we should probably spec out what more we expect. 

The queries can be passed as a JSON-ified q parameter on view data requests, so it's potentially automateable. I'd hoped to build it into a resource path, but sadly the Restlets framework doesn't allow that. See: http://stackoverflow.com/questions/33289700/recursive-url-routing-in-restlet
