### ISSUE TITLE
[Feature Request] Add Live links as new attribute data type 

### ISSUE THREAD

**Issue by cyang3** [pughlab/tracker#180]
Is it possible to add a feature allowing live/clickable links as a data type?

**Comment by morungos** [comment]
Anything is possible :-)

**Comment by morungos** [comment]
What do you think about this happening automatically? i.e., anything beginning http://... https://... getting turned into a link.

**Comment by cyang3** [comment]
Even better!

**Comment by tjpugh** [comment]
That would be good. Maybe also include smb:// and ftp://

- Trevor

On Apr 4, 2016, at 7:43 PM, Stuart Watt <notifications@github.com<mailto:notifications@github.com>> wrote:


What do you think about this happening automatically? i.e., anything beginning http://... https://... getting turned into a link.
