### ISSUE TITLE
NPE looking for tracker.js

### ISSUE THREAD

**Issue by morungos** [pughlab/tracker#3]
Reported by @morgantaschuk

**Comment by morungos** [comment]
This is being searched for in the classpath. That is probably stupid. We might very well want to externalize.

**Comment by morgantaschuk** [comment]
Welcome back?

It seems to be NPE because it's looking for a 'tracker.js' file in ScheduledJob class. The only tracker.js I can find is in sqlite3 node_modules dir. Do you need me to provide more info about how to replicate or are you good?

**Comment by morungos** [comment]
:-) 

I've just pushed a small commit that deals with the NPE. This is a fairly new part of the system, which I'm adding to make integration with other applications possible. But it ought to be optional and that was my mistake. Now a missing file shouldn't cause any issues.

**Comment by morgantaschuk** [comment]
Awesome, thanks for the fix.
