### ISSUE TITLE
Can't specify a port in usual Jetty way

### ISSUE THREAD

**Issue by morungos** [pughlab/tracker#4]
Command: 

```
mvn -Djetty.http.port=9999 jetty:run
```

And still the server starts on port 8080.

**Comment by morungos** [comment]
In a typical production deployment, we'd use a more advanced `jetty.xml` than the one used here with Maven, and this can do all sorts of extra configuration.

**Comment by morungos** [comment]
Ah. The Jetty Maven plugin appears to have silently changed the parameter to `jetty.port` when nobody was looking. The following command does work:

`mvn -Djetty.port=9999 jetty:run`

Found in: http://stackoverflow.com/questions/3334454/maven-pom-how-to-make-the-jetty-port-changeable-so-that-it-can-be-retrieved-l

See the comment above, though. Maven is really only intended for development. We'd use a more complete `jetty.xml` to do something better in production, or reverse proxy and SSL strip for security. My guess is that someone "helpfully" "simplified" the use of properties when they dropped the SSL support from the Maven plugin.

**Comment by morgantaschuk** [comment]
Lovely. Thanks again.
