### ISSUE TITLE
Serve files from the war not from the file system

### ISSUE THREAD

**Issue by morgantaschuk** [pughlab/tracker#5]
Clean checkout:

```
git clone git@github.com:pughlab/tracker.git
cd tracker
mvn clean install
mvn -Djetty.port=9999 jetty:run
```

And then I go to http://localhost:9999

![screen shot 2015-06-22 at 11 20 36 am](https://cloud.githubusercontent.com/assets/1746206/8285350/c32789ca-18d0-11e5-9254-af95496e19ca.png)

Here's what Jetty has to say about it:

```
FINE: batch acquisition of 1 triggers
Jun 22, 2015 11:20:00 AM org.quartz.core.QuartzSchedulerThread run
FINE: batch acquisition of 0 triggers
Jun 22, 2015 11:20:00 AM org.quartz.core.JobRunShell run
FINE: Calling execute on job DEFAULT.scheduledJobDetail
Jun 22, 2015 11:20:00 AM ca.uhnresearch.pughlab.tracker.scheduling.ScheduledJob execute
INFO: Scheduled ping
Jun 22, 2015 11:20:00 AM org.quartz.core.QuartzSchedulerThread run
FINE: batch acquisition of 0 triggers
Jun 22, 2015 11:20:14 AM org.restlet.engine.log.LogFilter afterHandle
INFO: 2015-06-22	11:20:14	0:0:0:0:0:0:0:1	-	0:0:0:0:0:0:0:1	9999	GET	/	-	404	439	http://localhost:9999	Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.124 Safari/537.36	-
```

**Comment by morungos** [comment]
Strange indeed, as I'm getting:

```
Jun 22, 2015 11:46:45 AM org.restlet.engine.log.LogFilter afterHandle
INFO: 2015-06-22	11:46:45	0:0:0:0:0:0:0:1	-	0:0:0:0:0:0:0:1	9999	GET	/	-	200	8389	0	1	http://localhost:9999	Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.81 Safari/537.36	-
```

**Comment by morungos** [comment]
The slight log format difference is also an interesting one. There seem to be two extra numeric fields. Maven should be better than this.

**Comment by morgantaschuk** [comment]
Running Mac OSX 10.10.3, Maven 3.3.3, Oracle Java 1.8.0_45

**Comment by morungos** [comment]
OK, the missing fields are likely an artifact of the 404, AFAICT: https://github.com/restlet/restlet-framework-java/blame/master/modules/org.restlet/src/org/restlet/service/LogService.java. So we still need to figure the 404. 

@morgantaschuk: can you post a full startup log? I know it's verbose. Email me if it's easier (just don't zip -- they get stripped by work email).

**Comment by morungos** [comment]
I have the same OSX and Maven, but not the same Java. So I better ask for the upgrade to test for that, though I will be a bit miffed if that's the cause :-(

**Comment by morungos** [comment]
Okay. Stupid stupid me. There's an absolute path reference in the Spring config here: https://github.com/pughlab/tracker/blob/develop/src/main/webapp/WEB-INF/applicationContext.xml#L36, which is completely awful. That should be an automatic thing. 

I do recall having bad issues with getting classpath serving to work, but it needs to, so let's change the title on the issue and engage with it.

**Comment by morgantaschuk** [comment]
Ha. Nice one. "Trust No One", not even oneself. Did you still want the startup log?

**Comment by morungos** [comment]
No need. As soon as I changed the URL value I could replicate it. Now I just need to fix it, and this was a nasty corner of restlets, so I'll need a bit of time and luck.

**Comment by morgantaschuk** [comment]
Luck!

**Comment by morungos** [comment]
Coming to the conclusion that the Maven jetty plugin is (a) a complete mess, and (b) beyond redemption. Really I need some easy way to kick off the webapp for development, but since jetty:run is too dumb to use additional resource paths (which jetty:run-war and jetty:run-exploded do) and can't handle the `ResourceCollection` either, we're a bit stuck. It's not clear why these don't work, but I suspect they're not playing nicely with whatever Restlets do with classloading magic to find resources.

In addition, we also need to redirect / -> /index.html, and that doesn't work either, probably for similar reasons (i.e., whatever classloader is used by Restlets isn't finding resources right). 

In the meantime, at least `jetty:run-exploded` can be made to sort of work. It's just bad for development.
